name: skip-toolchains ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  skip-toolchains:
    runs-on: macos-13
    steps:
      - name: "Ubuntu 20.04 Swift 5.6 x86_64 cross-compile"
        run: |
          brew install swift-toolchains/tap/spm-dest-5.6-x86_64-ubuntu20.04
          swift package init --type executable --name clidemo56
          swift build \
              --destination $(brew --prefix)/lib/swift/dst/x86_64-unknown-linux/swift-5.6-ubuntu20.04.xtoolchain/destination.json \
              --static-swift-stdlib \
              -Xswiftc "-static-executable" || echo Failed
          file .build/x86_64-unknown-linux-gnu/debug/clidemo56 || echo Failed

      - name: "Ubuntu 20.04 Swift 5.9 x86_64 cross-compile"
        run: |
          brew install swift-toolchains/tap/spm-dest-5.9-x86_64-ubuntu20.04
          swift package init --type executable --name clidemo59
          swift build \
              --destination $(brew --prefix)/lib/swift/dst/x86_64-unknown-linux/swift-5.9-ubuntu20.04.xtoolchain/destination.json \
              --static-swift-stdlib \
              -Xswiftc "-static-executable"
          file .build/x86_64-unknown-linux-gnu/debug/clidemo59


